'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { apiUrl as api } from '../../../../api';
type Task = { id:string; title:string; status:string; dueAt?:string };
type Comment = { id:string; body:string; createdAt:string };
export default function Tasks() {
 const { id } = useParams<{id:string}>(); const [tasks,setTasks]=useState<Task[]>([]); const [comments,setComments]=useState<Record<string,Comment[]>>({}); const [message,setMessage]=useState('');
 const headers=()=>({Authorization:`Bearer ${sessionStorage.getItem('accessToken')||''}`});
 const load=()=>fetch(`${api}/weddings/${id}`,{headers:headers()}).then(r=>r.json()).then(w=>setTasks(w.tasks||[]));
 const loadComments=(taskId:string)=>fetch(`${api}/weddings/${id}/tasks/${taskId}/comments`,{headers:headers()}).then(r=>r.json()).then(data=>setComments(old=>({...old,[taskId]:data})));
 useEffect(()=>{load();},[id]);
 async function changeStatus(taskId:string,status:string){const r=await fetch(`${api}/weddings/${id}/tasks/${taskId}`,{method:'PATCH',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({status})});if(r.ok){setMessage('Estado actualizado');load();}else setMessage('No se pudo actualizar la tarea');}
 async function addComment(e:FormEvent<HTMLFormElement>,taskId:string){e.preventDefault();const form=e.currentTarget;const body=new FormData(form).get('body')?.toString().trim();if(!body)return;const r=await fetch(`${api}/weddings/${id}/tasks/${taskId}/comments`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({body})});if(r.ok){form.reset();setMessage('Comentario agregado');loadComments(taskId);}else setMessage('No se pudo agregar el comentario');}
 async function attach(e:FormEvent<HTMLFormElement>,taskId:string){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);data.set('taskId',taskId);const r=await fetch(`${api}/weddings/${id}/files`,{method:'POST',headers:headers(),body:data});if(r.ok){form.reset();setMessage('Archivo adjuntado a la tarea');}else setMessage('No se pudo adjuntar el archivo (máximo 10 MB)');}
 return <main className="mx-auto max-w-5xl p-6"><p className="text-xs tracking-[.2em] text-rose">SEGUIMIENTO</p><h1 className="mt-2 font-serif text-4xl">Tareas y comentarios</h1>{message&&<p className="mt-3 text-sm text-sage">{message}</p>}<div className="mt-6 space-y-4">{tasks.map(task=><article className="rounded-3xl bg-white p-5 shadow-sm" key={task.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{task.title}</h2>{task.dueAt&&<p className="text-xs text-stone-500">Vence: {new Date(task.dueAt).toLocaleDateString('es-MX')}</p>}</div><select aria-label={`Estado de ${task.title}`} className="rounded-lg border p-2" value={task.status} onChange={e=>changeStatus(task.id,e.target.value)}><option value="TODO">Pendiente</option><option value="IN_PROGRESS">En proceso</option><option value="DONE">Completada</option><option value="CANCELLED">Cancelada</option></select></div><div className="mt-4 border-t pt-4"><button className="text-sm font-medium text-rose underline" onClick={()=>loadComments(task.id)}>Ver comentarios</button>{(comments[task.id]||[]).map(comment=><p className="mt-2 rounded-lg bg-blush/30 p-2 text-sm" key={comment.id}>{comment.body}</p>)}<form className="mt-3 flex gap-2" onSubmit={e=>addComment(e,task.id)}><input className="min-w-0 flex-1 rounded-lg border p-2 text-sm" name="body" placeholder="Escribe un comentario"/><button className="rounded-lg bg-sage px-3 text-sm text-white">Comentar</button></form><form className="mt-3 flex flex-wrap items-center gap-2" onSubmit={e=>attach(e,task.id)}><input name="file" type="file" required className="text-sm"/><button className="rounded-lg border border-sage px-3 py-2 text-sm text-sage">Adjuntar archivo</button></form></div></article>)}</div>{!tasks.length&&<p className="mt-6 rounded-2xl bg-white p-5">Esta boda aún no tiene tareas.</p>}</main>;
}
