import { Body, CanActivate, Controller, ExecutionContext, Injectable, Module, Post, Req, Res, UnauthorizedException } from '@nestjs/common';
import { JwtModule, JwtService } from '@nestjs/jwt';
import { ApiTags } from '@nestjs/swagger';
import * as argon2 from 'argon2';
import { createHash, randomBytes } from 'crypto';
import { IsEmail, IsString, MinLength } from 'class-validator';
import { PrismaModule, PrismaService } from './prisma';
class LoginDto { @IsEmail() email!: string; @IsString() @MinLength(8) password!: string; }
@Injectable() export class AuthGuard implements CanActivate { constructor(private jwt: JwtService) {} canActivate(c: ExecutionContext) { const token=c.switchToHttp().getRequest().headers.authorization?.replace('Bearer ',''); if(!token) throw new UnauthorizedException(); try { c.switchToHttp().getRequest().user=this.jwt.verify(token); return true; } catch { throw new UnauthorizedException('Sesión inválida o vencida'); } } }
@Injectable() export class AuthService { constructor(private prisma:PrismaService, private jwt:JwtService){} private hash(token:string){return createHash('sha256').update(token).digest('hex')} private refreshToken(){return randomBytes(48).toString('base64url')} private cookie(res:any,token:string){res.cookie('bodas_refresh',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:1000*60*60*24*30})} private access(user:{id:string;role:string}){return this.jwt.sign({sub:user.id,role:user.role})} async login(dto:LoginDto,res:any){const user=await this.prisma.user.findUnique({where:{email:dto.email}});if(!user||!user.active||!(await argon2.verify(user.passwordHash,dto.password)))throw new UnauthorizedException('Correo o contraseña incorrectos');const refresh=this.refreshToken();await this.prisma.session.create({data:{userId:user.id,tokenHash:this.hash(refresh),expiresAt:new Date(Date.now()+1000*60*60*24*30)}});this.cookie(res,refresh);return {accessToken:this.access(user),user:{id:user.id,name:user.name,role:user.role}}} async refresh(raw:string|undefined,res:any){if(!raw)throw new UnauthorizedException('Sesión no encontrada');const session=await this.prisma.session.findUnique({where:{tokenHash:this.hash(raw)},include:{user:true}});if(!session||session.revokedAt||session.expiresAt<=new Date()||!session.user.active)throw new UnauthorizedException('Sesión vencida');const next=this.refreshToken();await this.prisma.session.update({where:{id:session.id},data:{tokenHash:this.hash(next),expiresAt:new Date(Date.now()+1000*60*60*24*30)}});this.cookie(res,next);return {accessToken:this.access(session.user),user:{id:session.user.id,name:session.user.name,role:session.user.role}}} async logout(raw:string|undefined,res:any){if(raw)await this.prisma.session.updateMany({where:{tokenHash:this.hash(raw),revokedAt:null},data:{revokedAt:new Date()}});res.clearCookie('bodas_refresh',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax'});return {ok:true}} }
@ApiTags('auth') @Controller('auth') export class AuthController { constructor(private service:AuthService){} private refreshCookie(req:any){return req.headers.cookie?.split(';').map((item:string)=>item.trim()).find((item:string)=>item.startsWith('bodas_refresh='))?.slice('bodas_refresh='.length)} @Post('login') login(@Body() dto:LoginDto,@Res({passthrough:true})res:any){return this.service.login(dto,res)} @Post('refresh') refresh(@Req()req:any,@Res({passthrough:true})res:any){return this.service.refresh(this.refreshCookie(req),res)} @Post('logout') logout(@Req()req:any,@Res({passthrough:true})res:any){return this.service.logout(this.refreshCookie(req),res)} }
const jwtSecret=process.env.JWT_SECRET|| (process.env.NODE_ENV==='production' ? (()=>{throw new Error('JWT_SECRET es obligatorio en producción')})() : 'development-secret-change-me');
@Module({imports:[PrismaModule,JwtModule.register({secret:jwtSecret,signOptions:{expiresIn:'15m'}})],providers:[AuthService,AuthGuard],controllers:[AuthController],exports:[AuthGuard,JwtModule]}) export class AuthModule {}
