import { BadRequestException, Injectable, InternalServerErrorException } from '@nestjs/common';
import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'crypto';
import nodemailer from 'nodemailer';

@Injectable()
export class NotificationService {
  private key(){return createHash('sha256').update(process.env.INVITATION_TOKEN_SECRET || process.env.JWT_SECRET || 'development-invitation-secret').digest()}
  encrypt(token:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key(),iv);const body=Buffer.concat([cipher.update(token,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64url')}
  decrypt(value:string){try{const data=Buffer.from(value,'base64url');const decipher=createDecipheriv('aes-256-gcm',this.key(),data.subarray(0,12));decipher.setAuthTag(data.subarray(12,28));return Buffer.concat([decipher.update(data.subarray(28)),decipher.final()]).toString('utf8')}catch{throw new BadRequestException('Esta invitación debe regenerarse antes de enviarla')}}
  link(token:string){return `${(process.env.PUBLIC_APP_URL || process.env.WEB_ORIGIN || 'http://localhost:3000').replace(/\/$/,'')}/invitacion/${token}`}
  async sendEmail(to:string, link:string, couple:string){if(!process.env.SMTP_HOST || !process.env.SMTP_FROM)throw new InternalServerErrorException('SMTP no está configurado');const transport=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}:undefined});await transport.sendMail({from:process.env.SMTP_FROM,to,subject:`Invitación de ${couple}`,text:`Nos encantará celebrar contigo. Consulta tu invitación y confirma tu asistencia: ${link}`,html:`<p>Nos encantará celebrar contigo.</p><p><a href="${link}">Consulta tu invitación y confirma tu asistencia</a></p>`})}
  async sendWhatsApp(to:string, link:string, couple:string){if(!process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_AUTH_TOKEN || !process.env.TWILIO_WHATSAPP_FROM)throw new InternalServerErrorException('Twilio WhatsApp no está configurado');const body=new URLSearchParams({From:`whatsapp:${process.env.TWILIO_WHATSAPP_FROM}`,To:`whatsapp:${to}`,Body:`Hola, nos encantará celebrar contigo. Invitación de ${couple}: ${link}`});const auth=Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64');const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new InternalServerErrorException('Twilio rechazó el envío de WhatsApp')}
}
