import { Body, Controller, GoneException, Injectable, NotFoundException, Param, Post, Get, Module, BadRequestException } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { createHash } from 'crypto';
import { IsIn, IsInt, IsOptional, IsString, Max, Min } from 'class-validator';
import { InvitationStatus, RsvpStatus } from '@prisma/client';
import { PrismaModule, PrismaService } from './prisma';
class RsvpDto { @IsIn(['ACCEPTED','DECLINED']) status!:RsvpStatus; @IsInt() @Min(0) @Max(20) attendeeCount!:number; @IsOptional() @IsString() message?:string; }
const tokenHash=(token:string)=>createHash('sha256').update(token).digest('hex');
@Injectable() export class RsvpService { constructor(private prisma:PrismaService){} async invitation(token:string){ const invite=await this.prisma.invitation.findUnique({where:{tokenHash:tokenHash(token)},include:{group:{include:{guests:true}},wedding:true,response:true}});if(!invite)throw new NotFoundException('Esta invitación no es válida');if(invite.status==='REVOKED')throw new GoneException('Este enlace fue revocado');if(invite.status!==InvitationStatus.PUBLISHED)throw new GoneException('Esta invitación aún no está disponible');if(!invite.wedding.isPublished)throw new GoneException('La invitación está en preparación');return {couple:invite.wedding.title,date:invite.wedding.date,timezone:invite.wedding.timezone,group:invite.group.name,maxPasses:invite.group.maxPasses,response:invite.response,coverImageUrl:invite.wedding.coverImageUrl,coverSubtitle:invite.wedding.coverSubtitle,ceremonyVenue:invite.wedding.ceremonyVenue,receptionVenue:invite.wedding.receptionVenue,dressCode:invite.wedding.dressCode,program:invite.wedding.program,giftsInfo:invite.wedding.giftsInfo,galleryUrls:(invite.wedding.galleryUrls||invite.wedding.galleryUrl||'').split(/\r?\n/).filter(Boolean)};}
 async rsvp(token:string,d:RsvpDto){return this.prisma.$transaction(async tx=>{const invite=await tx.invitation.findUnique({where:{tokenHash:tokenHash(token)},include:{group:true,response:true}});if(!invite||invite.status==='REVOKED')throw new NotFoundException('Esta invitación no es válida');if(invite.status!==InvitationStatus.PUBLISHED)throw new GoneException('Invitación cerrada');if(invite.responseDeadline&&invite.responseDeadline<new Date())throw new GoneException('Terminó el plazo para responder');if(invite.response&&!invite.allowChanges)throw new GoneException('Esta respuesta ya no admite cambios');if(d.status==='DECLINED'&&d.attendeeCount!==0)throw new BadRequestException('Un rechazo debe registrar cero asistentes');if(d.status==='ACCEPTED'&&(d.attendeeCount<1||d.attendeeCount>invite.group.maxPasses))throw new BadRequestException(`Selecciona entre 1 y ${invite.group.maxPasses} asistentes`);const data={status:d.status,attendeeCount:d.attendeeCount,message:d.message};const response=invite.response?await tx.rsvpResponse.update({where:{invitationId:invite.id},data}):await tx.rsvpResponse.create({data:{invitationId:invite.id,...data}});await tx.rsvpHistory.create({data:{invitationId:invite.id,...data}});return {status:response.status,attendeeCount:response.attendeeCount,updatedAt:response.updatedAt};})}}
@ApiTags('invitación pública') @Controller('public/invitations') export class PublicController {constructor(private service:RsvpService){} @Get(':token') get(@Param('token')t:string){return this.service.invitation(t)} @Post(':token/rsvp') rsvp(@Param('token')t:string,@Body()d:RsvpDto){return this.service.rsvp(t,d)} }
@Module({imports:[PrismaModule],providers:[RsvpService],controllers:[PublicController]}) export class PublicModule{}
