import { Body, Controller, ForbiddenException, Get, Injectable, Module, NotFoundException, Param, Patch, Post, Req, Res, UploadedFile, UseGuards, UseInterceptors } from '@nestjs/common';
import { resolve } from 'path';
import { FileInterceptor } from '@nestjs/platform-express';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { IsArray, IsBoolean, IsDateString, IsIn, IsInt, IsOptional, IsString, Max, Min } from 'class-validator';
import { createHash, randomBytes } from 'crypto';
import * as argon2 from 'argon2';
import { Prisma, Role } from '@prisma/client';
import { AuthGuard, AuthModule } from './auth';
import { PrismaModule, PrismaService } from './prisma';
type CurrentUser={sub:string;role:Role};
class CreateWeddingDto { @IsString() title!:string; @IsOptional() @IsDateString() date?:string; @IsOptional() @IsString() timezone?:string; @IsOptional() @IsString() currency?:string; @IsOptional() @IsString() partnerOneName?:string; @IsOptional() @IsString() partnerTwoName?:string; @IsOptional() @IsString() email?:string; @IsOptional() @IsString() phone?:string; @IsOptional() @IsInt() estimatedGuests?:number; @IsOptional() @IsString() style?:string; }
class CreateTaskDto { @IsString() title!:string; @IsString() category!:string; @IsOptional() @IsDateString() dueAt?:string; @IsOptional() @IsInt() @Min(1) @Max(3) priority?:number; @IsOptional() @IsBoolean() internalOnly?:boolean; }
class CreateGroupDto { @IsString() name!:string; @IsInt() @Min(1) @Max(20) maxPasses!:number; @IsOptional() @IsString() contactPhone?:string; }
class CreateObligationDto { @IsString() description!:string; @IsIn(['RECEIVABLE','PAYABLE']) direction!: 'RECEIVABLE'|'PAYABLE'; @IsString() amount!:string; @IsOptional() @IsDateString() dueDate?:string; }
class AddPaymentDto { @IsString() amount!:string; @IsString() idempotencyKey!:string; @IsOptional() @IsString() reference?:string; }
class CreateInvitationDto { @IsString() groupId!:string; @IsOptional() @IsDateString() responseDeadline?:string; }
class CreateGuestDto { @IsString() firstName!:string; @IsOptional() @IsString() lastName?:string; @IsOptional() @IsString() phone?:string; @IsOptional() @IsString() email?:string; @IsOptional() @IsString() dietaryNotes?:string; }
class ImportGuestsDto { @IsArray() rows!:Array<Record<string,string>>; }
class VendorDto { @IsString() name!:string; @IsString() category!:string; @IsOptional() @IsString() contactName?:string; @IsOptional() @IsString() phone?:string; @IsOptional() @IsString() email?:string; @IsOptional() @IsString() services?:string; }
class VendorContractDto { @IsString() vendorId!:string; @IsString() service!:string; @IsOptional() @IsString() quotedAmount?:string; @IsOptional() @IsString() contractedAmount?:string; @IsOptional() @IsString() currency?:string; @IsOptional() @IsString() conditions?:string; @IsOptional() @IsString() quoteDetails?:string; @IsOptional() @IsString() contractReference?:string; @IsOptional() @IsIn(['DRAFT','QUOTED','CONTRACTED','COMPLETED','CANCELLED']) status?:'DRAFT'|'QUOTED'|'CONTRACTED'|'COMPLETED'|'CANCELLED'; @IsOptional() @IsDateString() signedAt?:string; }
class VendorContractUpdateDto { @IsOptional() @IsString() service?:string; @IsOptional() @IsString() quotedAmount?:string; @IsOptional() @IsString() contractedAmount?:string; @IsOptional() @IsString() currency?:string; @IsOptional() @IsString() conditions?:string; @IsOptional() @IsString() quoteDetails?:string; @IsOptional() @IsString() contractReference?:string; @IsOptional() @IsIn(['DRAFT','QUOTED','CONTRACTED','COMPLETED','CANCELLED']) status?:'DRAFT'|'QUOTED'|'CONTRACTED'|'COMPLETED'|'CANCELLED'; @IsOptional() @IsDateString() signedAt?:string; }
class VendorContractPaymentDto { @IsString() amount!:string; @IsOptional() @IsString() reference?:string; @IsOptional() @IsString() notes?:string; }
class ActivityDto { @IsString() title!:string; @IsString() type!:string; @IsDateString() startsAt!:string; @IsOptional() @IsDateString() endsAt?:string; @IsOptional() @IsString() responsible?:string; @IsOptional() @IsString() notes?:string; }
class TaskUpdateDto { @IsIn(['TODO','IN_PROGRESS','DONE','CANCELLED']) status!: 'TODO'|'IN_PROGRESS'|'DONE'|'CANCELLED'; @IsOptional() @IsBoolean() internalOnly?:boolean; }
class CommentDto { @IsString() body!:string; }
class TeamUserDto { @IsString() name!:string; @IsString() email!:string; @IsIn(['PLANNER','ASSISTANT','COUPLE']) role!: 'PLANNER'|'ASSISTANT'|'COUPLE'; @IsString() password!:string; }
class AssignDto { @IsString() userId!:string; @IsOptional() @IsBoolean() canViewFinance?:boolean; }
class CoupleDto { @IsString() userId!:string; }
class InvitationUpdateDto { @IsIn(['PUBLISHED','CLOSED','REVOKED']) status!: 'PUBLISHED'|'CLOSED'|'REVOKED'; }
class PublishDto { @IsOptional() @IsString() ceremonyVenue?:string; @IsOptional() @IsString() receptionVenue?:string; @IsOptional() @IsString() coverImageUrl?:string; @IsOptional() @IsString() coverSubtitle?:string; @IsOptional() @IsString() dressCode?:string; @IsOptional() @IsString() program?:string; @IsOptional() @IsString() giftsInfo?:string; @IsOptional() @IsString() galleryUrl?:string; @IsOptional() @IsString() galleryUrls?:string; @IsOptional() @IsBoolean() isPublished?:boolean; }
@Injectable() export class WeddingAccess { constructor(private prisma:PrismaService){} async assert(user:CurrentUser,weddingId:string, finance=false){ const wedding=await this.prisma.wedding.findUnique({where:{id:weddingId}}); if(!wedding) throw new NotFoundException('Boda no encontrada'); if(user.role==='ADMIN') return wedding; if(user.role==='COUPLE' && wedding.coupleUserId===user.sub) return wedding; const assignment=await this.prisma.weddingAssignment.findUnique({where:{weddingId_userId:{weddingId,userId:user.sub}}}); if(!assignment || (finance && !assignment.canViewFinance)) throw new ForbiddenException('No tienes acceso a esta boda'); return wedding; } }
@ApiTags('bodas') @ApiBearerAuth() @UseGuards(AuthGuard) @Controller('weddings') export class WeddingsController { constructor(private prisma:PrismaService,private access:WeddingAccess){}
 @Get('dashboard/summary') async summary(@Req()r:any){const u=r.user as CurrentUser;const scope=u.role==='ADMIN'?{}:u.role==='COUPLE'?{coupleUserId:u.sub}:{assignments:{some:{userId:u.sub}}};const weddings=await this.prisma.wedding.findMany({where:scope,include:{tasks:true,invitations:{include:{response:true}},obligations:true}});const now=new Date();const tasks=weddings.flatMap(w=>w.tasks).filter(t=>t.status!=='DONE'&&t.status!=='CANCELLED'&&!!t.dueAt&&t.dueAt<=new Date(now.getTime()+7*86400000));const payments=weddings.flatMap(w=>w.obligations).filter(o=>o.status!=='PAID'&&!!o.dueDate&&o.dueDate<=new Date(now.getTime()+7*86400000));const invitations=weddings.flatMap(w=>w.invitations);return {activeWeddings:weddings.length,urgentTasks:tasks.length,duePayments:payments.length,pendingRsvp:invitations.filter(i=>!i.response||i.response.status==='PENDING').length,upcomingTasks:tasks.slice(0,6)}}
 @Get() async list(@Req() r:any){const u=r.user as CurrentUser; if(u.role==='ADMIN') return this.prisma.wedding.findMany({orderBy:{date:'asc'}}); if(u.role==='COUPLE') return this.prisma.wedding.findMany({where:{coupleUserId:u.sub}}); return this.prisma.wedding.findMany({where:{assignments:{some:{userId:u.sub}}}})}
 @Post() async create(@Req()r:any,@Body()d:CreateWeddingDto){if(r.user.role!=='ADMIN') throw new ForbiddenException();const {partnerOneName,partnerTwoName,email,phone,estimatedGuests,style,...wedding}=d;return this.prisma.wedding.create({data:{...wedding,date:wedding.date?new Date(wedding.date):undefined,client:partnerOneName?{create:{partnerOneName,partnerTwoName,email,phone,estimatedGuests,style}}:undefined}})}
 @Get(':id/portal') async portal(@Req()r:any,@Param('id')id:string){await this.access.assert(r.user,id);if(r.user.role!=='COUPLE')throw new ForbiddenException('Este portal es exclusivo para la pareja');return this.prisma.wedding.findUnique({where:{id},select:{id:true,title:true,date:true,timezone:true,isPublished:true,ceremonyVenue:true,receptionVenue:true,coverImageUrl:true,coverSubtitle:true,dressCode:true,program:true,giftsInfo:true,galleryUrl:true,galleryUrls:true,tasks:{where:{internalOnly:false},orderBy:{dueAt:'asc'},select:{id:true,title:true,category:true,dueAt:true,status:true}}}})}
 @Get(':id') async detail(@Req()r:any,@Param('id')id:string){await this.access.assert(r.user,id);if(r.user.role==='COUPLE')throw new ForbiddenException('Usa el portal de pareja');return this.prisma.wedding.findUnique({where:{id},include:{coupleUser:{select:{id:true,name:true,email:true,role:true}},tasks:{orderBy:{dueAt:'asc'}},guestGroups:{include:{invitation:{include:{response:true}},guests:true}},obligations:{include:{payments:true},orderBy:{dueDate:'asc'}},assignments:{include:{user:{select:{id:true,name:true,email:true,role:true}}}},_count:{select:{guestGroups:true,invitations:true}}}})}
 @Post(':id/tasks') async task(@Req()r:any,@Param('id')id:string,@Body()d:CreateTaskDto){await this.access.assert(r.user,id); if(r.user.role==='COUPLE') throw new ForbiddenException(); return this.prisma.task.create({data:{...d,weddingId:id,dueAt:d.dueAt?new Date(d.dueAt):undefined}})}
 @Patch(':id/tasks/:taskId') async taskStatus(@Req()r:any,@Param('id')id:string,@Param('taskId')taskId:string,@Body()d:TaskUpdateDto){await this.access.assert(r.user,id);const task=await this.prisma.task.findFirst({where:{id:taskId,weddingId:id}});if(!task)throw new NotFoundException();if(r.user.role==='COUPLE'&&(task.internalOnly||d.internalOnly!==undefined))throw new ForbiddenException('No puedes modificar esta tarea');return this.prisma.task.update({where:{id:taskId},data:d})}
 @Patch(':id/portal/tasks/:taskId') async portalTask(@Req()r:any,@Param('id')id:string,@Param('taskId')taskId:string,@Body()d:TaskUpdateDto){await this.access.assert(r.user,id);if(r.user.role!=='COUPLE')throw new ForbiddenException();const task=await this.prisma.task.findFirst({where:{id:taskId,weddingId:id,internalOnly:false}});if(!task)throw new NotFoundException('Tarea autorizada no encontrada');return this.prisma.task.update({where:{id:taskId},data:{status:d.status}})}
 @Post(':id/tasks/:taskId/comments') async comment(@Req()r:any,@Param('id')id:string,@Param('taskId')taskId:string,@Body()d:CommentDto){await this.access.assert(r.user,id);const task=await this.prisma.task.findFirst({where:{id:taskId,weddingId:id}});if(!task)throw new NotFoundException();return this.prisma.taskComment.create({data:{taskId,authorId:r.user.sub,body:d.body}})}
 @Get(':id/tasks/:taskId/comments') async comments(@Req()r:any,@Param('id')id:string,@Param('taskId')taskId:string){await this.access.assert(r.user,id);const task=await this.prisma.task.findFirst({where:{id:taskId,weddingId:id}});if(!task)throw new NotFoundException();return this.prisma.taskComment.findMany({where:{taskId},orderBy:{createdAt:'asc'}})}
 @Post(':id/team') async assign(@Req()r:any,@Param('id')id:string,@Body()d:AssignDto){if(r.user.role!=='ADMIN')throw new ForbiddenException();await this.access.assert(r.user,id);return this.prisma.weddingAssignment.upsert({where:{weddingId_userId:{weddingId:id,userId:d.userId}},update:{canViewFinance:d.canViewFinance||false},create:{weddingId:id,userId:d.userId,canViewFinance:d.canViewFinance||false}})}
 @Post(':id/couple') async assignCouple(@Req()r:any,@Param('id')id:string,@Body()d:CoupleDto){if(r.user.role!=='ADMIN')throw new ForbiddenException();await this.access.assert(r.user,id);const user=await this.prisma.user.findFirst({where:{id:d.userId,role:'COUPLE',active:true}});if(!user)throw new NotFoundException('Cuenta de pareja no encontrada');return this.prisma.wedding.update({where:{id},data:{coupleUserId:user.id},select:{id:true,coupleUser:{select:{id:true,name:true,email:true,role:true}}}})}
 @Get(':id/files') async files(@Req()r:any,@Param('id')id:string){await this.access.assert(r.user,id);return this.prisma.fileRecord.findMany({where:{weddingId:id},orderBy:{createdAt:'desc'}})}
 @Post(':id/files') @UseInterceptors(FileInterceptor('file',{dest:'uploads',limits:{fileSize:10*1024*1024}})) async file(@Req()r:any,@Param('id')id:string,@Body('taskId')taskId:string|undefined,@Body('contractId')contractId:string|undefined,@UploadedFile()file:any){await this.access.assert(r.user,id);if(!file)throw new NotFoundException('Archivo requerido');if(taskId){const task=await this.prisma.task.findFirst({where:{id:taskId,weddingId:id}});if(!task)throw new NotFoundException('Tarea no encontrada')}if(contractId){const contract=await this.prisma.vendorContract.findFirst({where:{id:contractId,weddingId:id}});if(!contract)throw new NotFoundException('Contratación no encontrada')}return this.prisma.fileRecord.create({data:{weddingId:id,taskId:taskId||undefined,contractId:contractId||undefined,name:file.originalname,mimeType:file.mimetype,path:file.path,visibility:'INTERNAL'}})}
 @Get(':id/files/:fileId/download') async download(@Req()r:any,@Param('id')id:string,@Param('fileId')fileId:string,@Res()res:any){await this.access.assert(r.user,id);const file=await this.prisma.fileRecord.findFirst({where:{id:fileId,weddingId:id}});if(!file)throw new NotFoundException('Archivo no encontrado');return res.download(resolve(file.path),file.name)}
 @Get(':id/activities') async activities(@Req()r:any,@Param('id')id:string){await this.access.assert(r.user,id);return this.prisma.activity.findMany({where:{weddingId:id},orderBy:{startsAt:'asc'}})}
 @Get(':id/contracts') async contracts(@Req()r:any,@Param('id')id:string){await this.access.assert(r.user,id,true);return this.prisma.vendorContract.findMany({where:{weddingId:id},include:{vendor:true,payments:{orderBy:{paidAt:'desc'}},files:true},orderBy:{createdAt:'desc'}})}
 @Post(':id/contracts') async createContract(@Req()r:any,@Param('id')id:string,@Body()d:VendorContractDto){await this.access.assert(r.user,id,true);if(r.user.role==='COUPLE')throw new ForbiddenException();const vendor=await this.prisma.vendor.findUnique({where:{id:d.vendorId}});if(!vendor)throw new NotFoundException('Proveedor no encontrado');return this.prisma.vendorContract.create({data:{weddingId:id,vendorId:d.vendorId,service:d.service,quotedAmount:d.quotedAmount?new Prisma.Decimal(d.quotedAmount):undefined,contractedAmount:d.contractedAmount?new Prisma.Decimal(d.contractedAmount):undefined,currency:d.currency||'MXN',conditions:d.conditions,quoteDetails:d.quoteDetails,contractReference:d.contractReference,status:d.status||'DRAFT',signedAt:d.signedAt?new Date(d.signedAt):undefined},include:{vendor:true,payments:true,files:true}})}
 @Patch(':id/contracts/:contractId') async updateContract(@Req()r:any,@Param('id')id:string,@Param('contractId')contractId:string,@Body()d:VendorContractUpdateDto){await this.access.assert(r.user,id,true);if(r.user.role==='COUPLE')throw new ForbiddenException();const contract=await this.prisma.vendorContract.findFirst({where:{id:contractId,weddingId:id}});if(!contract)throw new NotFoundException('Contratación no encontrada');const data:any={...d};if(d.quotedAmount!==undefined)data.quotedAmount=new Prisma.Decimal(d.quotedAmount);if(d.contractedAmount!==undefined)data.contractedAmount=new Prisma.Decimal(d.contractedAmount);if(d.signedAt!==undefined)data.signedAt=new Date(d.signedAt);return this.prisma.vendorContract.update({where:{id:contractId},data,include:{vendor:true,payments:true,files:true}})}
 @Post(':id/contracts/:contractId/payments') async contractPayment(@Req()r:any,@Param('id')id:string,@Param('contractId')contractId:string,@Body()d:VendorContractPaymentDto){await this.access.assert(r.user,id,true);if(r.user.role==='COUPLE')throw new ForbiddenException();return this.prisma.$transaction(async tx=>{const contract=await tx.vendorContract.findFirst({where:{id:contractId,weddingId:id}});if(!contract)throw new NotFoundException('Contratación no encontrada');const amount=new Prisma.Decimal(d.amount);if(amount.lte(0))throw new ForbiddenException('El pago debe ser mayor que cero');const next=contract.paidAmount.plus(amount);if(contract.contractedAmount&&next.gt(contract.contractedAmount))throw new ForbiddenException('El pago excede el importe contratado');const payment=await tx.vendorContractPayment.create({data:{contractId,amount,reference:d.reference,notes:d.notes}});await tx.vendorContract.update({where:{id:contractId},data:{paidAmount:next}});return payment})}
 @Post(':id/activities') async activity(@Req()r:any,@Param('id')id:string,@Body()d:ActivityDto){await this.access.assert(r.user,id);if(r.user.role==='COUPLE')throw new ForbiddenException();return this.prisma.activity.create({data:{...d,weddingId:id,startsAt:new Date(d.startsAt),endsAt:d.endsAt?new Date(d.endsAt):undefined}})}
 @Post(':id/groups') async group(@Req()r:any,@Param('id')id:string,@Body()d:CreateGroupDto){await this.access.assert(r.user,id);return this.prisma.guestGroup.create({data:{...d,weddingId:id}})}
 @Post(':id/groups/:groupId/guests') async guest(@Req()r:any,@Param('id')id:string,@Param('groupId')groupId:string,@Body()d:CreateGuestDto){await this.access.assert(r.user,id);const group=await this.prisma.guestGroup.findFirst({where:{id:groupId,weddingId:id}});if(!group)throw new NotFoundException('Familia no encontrada');return this.prisma.guest.create({data:{...d,groupId}})}
 @Post(':id/guests/import') async importGuests(@Req()r:any,@Param('id')id:string,@Body()d:ImportGuestsDto){await this.access.assert(r.user,id);const errors:Array<{row:number;message:string}>=[];let imported=0,skipped=0;await this.prisma.$transaction(async tx=>{for(let i=0;i<d.rows.length;i++){const row=d.rows[i],name=row.nombre?.trim(),family=row.familia?.trim();const passes=Number(row.pases||1);if(!name||!family||!Number.isInteger(passes)||passes<1){errors.push({row:i+2,message:'familia, nombre y pases entero positivo son obligatorios'});continue}let group=await tx.guestGroup.findFirst({where:{weddingId:id,name:family}});if(!group)group=await tx.guestGroup.create({data:{weddingId:id,name:family,maxPasses:passes,contactPhone:row.telefono||undefined}});const exists=await tx.guest.findFirst({where:{groupId:group.id,firstName:name,lastName:row.apellidos||undefined}});if(exists){skipped++;continue}await tx.guest.create({data:{groupId:group.id,firstName:name,lastName:row.apellidos||undefined,phone:row.telefono||undefined,email:row.correo||undefined,dietaryNotes:row.restricciones||undefined}});imported++}});return {imported,skipped,errors,policy:'Se omite duplicado sólo si coincide familia, nombre y apellidos; teléfono compartido no determina duplicidad.'}}
 @Post(':id/invitations') async invitation(@Req()r:any,@Param('id')id:string,@Body()d:CreateInvitationDto){await this.access.assert(r.user,id);const group=await this.prisma.guestGroup.findFirst({where:{id:d.groupId,weddingId:id}});if(!group)throw new NotFoundException('Familia no encontrada');const token=randomBytes(32).toString('base64url');const invitation=await this.prisma.invitation.create({data:{weddingId:id,groupId:group.id,tokenHash:createHash('sha256').update(token).digest('hex'),status:'PUBLISHED',responseDeadline:d.responseDeadline?new Date(d.responseDeadline):undefined}});return {id:invitation.id,token,publicPath:`/invitacion/${token}`}}
 @Patch(':id/invitations/:invitationId') async updateInvitation(@Req()r:any,@Param('id')id:string,@Param('invitationId')invitationId:string,@Body()d:InvitationUpdateDto){await this.access.assert(r.user,id);const found=await this.prisma.invitation.findFirst({where:{id:invitationId,weddingId:id}});if(!found)throw new NotFoundException('Invitación no encontrada');return this.prisma.invitation.update({where:{id:invitationId},data:{status:d.status}})}
 @Patch(':id/publish') async publish(@Req()r:any,@Param('id')id:string,@Body()d:PublishDto){await this.access.assert(r.user,id);if(r.user.role==='COUPLE')throw new ForbiddenException();return this.prisma.wedding.update({where:{id},data:d})}
 @Post(':id/obligations') async obligation(@Req()r:any,@Param('id')id:string,@Body()d:CreateObligationDto){await this.access.assert(r.user,id,true); return this.prisma.obligation.create({data:{weddingId:id,description:d.description,direction:d.direction,amount:new Prisma.Decimal(d.amount),dueDate:d.dueDate?new Date(d.dueDate):undefined}})}
 @Post(':id/obligations/:obligationId/payments') async pay(@Req()r:any,@Param('id')id:string,@Param('obligationId')oid:string,@Body()d:AddPaymentDto){await this.access.assert(r.user,id,true);return this.prisma.$transaction(async tx=>{const existing=await tx.payment.findUnique({where:{idempotencyKey:d.idempotencyKey}});if(existing)return existing;const ob=await tx.obligation.findFirst({where:{id:oid,weddingId:id}});if(!ob)throw new NotFoundException('Obligación no encontrada');const sum=ob.paidAmount.plus(new Prisma.Decimal(d.amount));if(sum.gt(ob.amount))throw new ForbiddenException('El pago excede el saldo');const payment=await tx.payment.create({data:{obligationId:oid,idempotencyKey:d.idempotencyKey,amount:new Prisma.Decimal(d.amount),paidAt:new Date(),reference:d.reference}});await tx.obligation.update({where:{id:oid},data:{paidAmount:sum,status:sum.eq(ob.amount)?'PAID':'PARTIAL'}});return payment})}
}
@ApiTags('proveedores') @ApiBearerAuth() @UseGuards(AuthGuard) @Controller('vendors') export class VendorsController {constructor(private prisma:PrismaService){} @Get() list(@Req()r:any){if(r.user.role==='COUPLE')throw new ForbiddenException();return this.prisma.vendor.findMany({orderBy:{name:'asc'}})} @Post() create(@Req()r:any,@Body()d:VendorDto){if(!['ADMIN','PLANNER'].includes(r.user.role))throw new ForbiddenException();return this.prisma.vendor.create({data:d})}}
@ApiTags('equipo') @ApiBearerAuth() @UseGuards(AuthGuard) @Controller('users') export class UsersController {constructor(private prisma:PrismaService){} @Get() list(@Req()r:any){if(r.user.role!=='ADMIN')throw new ForbiddenException();return this.prisma.user.findMany({select:{id:true,name:true,email:true,role:true,active:true}})} @Post() async create(@Req()r:any,@Body()d:TeamUserDto){if(r.user.role!=='ADMIN')throw new ForbiddenException();const {password,...user}=d;return this.prisma.user.create({data:{...user,passwordHash:await argon2.hash(password)}})}}
@Module({imports:[PrismaModule,AuthModule],controllers:[WeddingsController,VendorsController,UsersController],providers:[WeddingAccess],exports:[WeddingAccess]}) export class WeddingsModule{}
