import { Body, Controller, ForbiddenException, Get, Injectable, Module, NotFoundException, Param, Post, Req, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { IsArray, IsDateString, IsIn, IsInt, IsOptional, IsString, Max, Min } from 'class-validator';
import { createHash, randomBytes } from 'crypto';
import { Prisma, Role } from '@prisma/client';
import { AuthGuard, AuthModule } from './auth';
import { PrismaModule, PrismaService } from './prisma';
type CurrentUser={sub:string;role:Role};
class CreateWeddingDto { @IsString() title!:string; @IsOptional() @IsDateString() date?:string; @IsOptional() @IsString() timezone?:string; @IsOptional() @IsString() currency?:string; @IsOptional() @IsString() partnerOneName?:string; @IsOptional() @IsString() partnerTwoName?:string; @IsOptional() @IsString() email?:string; @IsOptional() @IsString() phone?:string; @IsOptional() @IsInt() estimatedGuests?:number; @IsOptional() @IsString() style?:string; }
class CreateTaskDto { @IsString() title!:string; @IsString() category!:string; @IsOptional() @IsDateString() dueAt?:string; @IsOptional() @IsInt() @Min(1) @Max(3) priority?:number; }
class CreateGroupDto { @IsString() name!:string; @IsInt() @Min(1) @Max(20) maxPasses!:number; @IsOptional() @IsString() contactPhone?:string; }
class CreateObligationDto { @IsString() description!:string; @IsIn(['RECEIVABLE','PAYABLE']) direction!: 'RECEIVABLE'|'PAYABLE'; @IsString() amount!:string; @IsOptional() @IsDateString() dueDate?:string; }
class AddPaymentDto { @IsString() amount!:string; @IsString() idempotencyKey!:string; @IsOptional() @IsString() reference?:string; }
class CreateInvitationDto { @IsString() groupId!:string; @IsOptional() @IsDateString() responseDeadline?:string; }
class CreateGuestDto { @IsString() firstName!:string; @IsOptional() @IsString() lastName?:string; @IsOptional() @IsString() phone?:string; @IsOptional() @IsString() email?:string; @IsOptional() @IsString() dietaryNotes?:string; }
class ImportGuestsDto { @IsArray() rows!:Array<Record<string,string>>; }
@Injectable() export class WeddingAccess { constructor(private prisma:PrismaService){} async assert(user:CurrentUser,weddingId:string, finance=false){ const wedding=await this.prisma.wedding.findUnique({where:{id:weddingId}}); if(!wedding) throw new NotFoundException('Boda no encontrada'); if(user.role==='ADMIN') return wedding; if(user.role==='COUPLE' && wedding.coupleUserId===user.sub) return wedding; const assignment=await this.prisma.weddingAssignment.findUnique({where:{weddingId_userId:{weddingId,userId:user.sub}}}); if(!assignment || (finance && !assignment.canViewFinance)) throw new ForbiddenException('No tienes acceso a esta boda'); return wedding; } }
@ApiTags('bodas') @ApiBearerAuth() @UseGuards(AuthGuard) @Controller('weddings') export class WeddingsController { constructor(private prisma:PrismaService,private access:WeddingAccess){}
 @Get() async list(@Req() r:any){const u=r.user as CurrentUser; if(u.role==='ADMIN') return this.prisma.wedding.findMany({orderBy:{date:'asc'}}); if(u.role==='COUPLE') return this.prisma.wedding.findMany({where:{coupleUserId:u.sub}}); return this.prisma.wedding.findMany({where:{assignments:{some:{userId:u.sub}}}})}
 @Post() async create(@Req()r:any,@Body()d:CreateWeddingDto){if(r.user.role!=='ADMIN') throw new ForbiddenException();const {partnerOneName,partnerTwoName,email,phone,estimatedGuests,style,...wedding}=d;return this.prisma.wedding.create({data:{...wedding,date:wedding.date?new Date(wedding.date):undefined,client:partnerOneName?{create:{partnerOneName,partnerTwoName,email,phone,estimatedGuests,style}}:undefined}})}
 @Get(':id') async detail(@Req()r:any,@Param('id')id:string){await this.access.assert(r.user,id);return this.prisma.wedding.findUnique({where:{id},include:{tasks:{orderBy:{dueAt:'asc'}},guestGroups:{include:{invitation:{include:{response:true}},guests:true}},obligations:{include:{payments:true},orderBy:{dueDate:'asc'}},_count:{select:{guestGroups:true,invitations:true}}}})}
 @Post(':id/tasks') async task(@Req()r:any,@Param('id')id:string,@Body()d:CreateTaskDto){await this.access.assert(r.user,id); if(r.user.role==='COUPLE') throw new ForbiddenException(); return this.prisma.task.create({data:{...d,weddingId:id,dueAt:d.dueAt?new Date(d.dueAt):undefined}})}
 @Post(':id/groups') async group(@Req()r:any,@Param('id')id:string,@Body()d:CreateGroupDto){await this.access.assert(r.user,id);return this.prisma.guestGroup.create({data:{...d,weddingId:id}})}
 @Post(':id/groups/:groupId/guests') async guest(@Req()r:any,@Param('id')id:string,@Param('groupId')groupId:string,@Body()d:CreateGuestDto){await this.access.assert(r.user,id);const group=await this.prisma.guestGroup.findFirst({where:{id:groupId,weddingId:id}});if(!group)throw new NotFoundException('Familia no encontrada');return this.prisma.guest.create({data:{...d,groupId}})}
 @Post(':id/guests/import') async importGuests(@Req()r:any,@Param('id')id:string,@Body()d:ImportGuestsDto){await this.access.assert(r.user,id);const errors:Array<{row:number;message:string}>=[];let imported=0,skipped=0;await this.prisma.$transaction(async tx=>{for(let i=0;i<d.rows.length;i++){const row=d.rows[i],name=row.nombre?.trim(),family=row.familia?.trim();const passes=Number(row.pases||1);if(!name||!family||!Number.isInteger(passes)||passes<1){errors.push({row:i+2,message:'familia, nombre y pases entero positivo son obligatorios'});continue}let group=await tx.guestGroup.findFirst({where:{weddingId:id,name:family}});if(!group)group=await tx.guestGroup.create({data:{weddingId:id,name:family,maxPasses:passes,contactPhone:row.telefono||undefined}});const exists=await tx.guest.findFirst({where:{groupId:group.id,firstName:name,lastName:row.apellidos||undefined}});if(exists){skipped++;continue}await tx.guest.create({data:{groupId:group.id,firstName:name,lastName:row.apellidos||undefined,phone:row.telefono||undefined,email:row.correo||undefined,dietaryNotes:row.restricciones||undefined}});imported++}});return {imported,skipped,errors,policy:'Se omite duplicado sólo si coincide familia, nombre y apellidos; teléfono compartido no determina duplicidad.'}}
 @Post(':id/invitations') async invitation(@Req()r:any,@Param('id')id:string,@Body()d:CreateInvitationDto){await this.access.assert(r.user,id);const group=await this.prisma.guestGroup.findFirst({where:{id:d.groupId,weddingId:id}});if(!group)throw new NotFoundException('Familia no encontrada');const token=randomBytes(32).toString('base64url');const invitation=await this.prisma.invitation.create({data:{weddingId:id,groupId:group.id,tokenHash:createHash('sha256').update(token).digest('hex'),status:'PUBLISHED',responseDeadline:d.responseDeadline?new Date(d.responseDeadline):undefined}});return {id:invitation.id,token,publicPath:`/invitacion/${token}`}}
 @Post(':id/obligations') async obligation(@Req()r:any,@Param('id')id:string,@Body()d:CreateObligationDto){await this.access.assert(r.user,id,true); return this.prisma.obligation.create({data:{weddingId:id,description:d.description,direction:d.direction,amount:new Prisma.Decimal(d.amount),dueDate:d.dueDate?new Date(d.dueDate):undefined}})}
 @Post(':id/obligations/:obligationId/payments') async pay(@Req()r:any,@Param('id')id:string,@Param('obligationId')oid:string,@Body()d:AddPaymentDto){await this.access.assert(r.user,id,true);return this.prisma.$transaction(async tx=>{const existing=await tx.payment.findUnique({where:{idempotencyKey:d.idempotencyKey}});if(existing)return existing;const ob=await tx.obligation.findFirst({where:{id:oid,weddingId:id}});if(!ob)throw new NotFoundException('Obligación no encontrada');const sum=ob.paidAmount.plus(new Prisma.Decimal(d.amount));if(sum.gt(ob.amount))throw new ForbiddenException('El pago excede el saldo');const payment=await tx.payment.create({data:{obligationId:oid,idempotencyKey:d.idempotencyKey,amount:new Prisma.Decimal(d.amount),paidAt:new Date(),reference:d.reference}});await tx.obligation.update({where:{id:oid},data:{paidAmount:sum,status:sum.eq(ob.amount)?'PAID':'PARTIAL'}});return payment})}
}
@Module({imports:[PrismaModule,AuthModule],controllers:[WeddingsController],providers:[WeddingAccess],exports:[WeddingAccess]}) export class WeddingsModule{}
